site_name: Renata Beroli
site_url: https://renataberoli.github.io/
nav:
  - Bug Catcher: 'projects/bug_catcher.md'
  - Dockgrid: 'projects/dockgrid.md'
  - Neobiome BIM: 'projects/neobiome.md'
  - Microbiome Reports: 'projects/reports.md'
  - Test Cases: 'projects/test_case.md'

theme:
  name: material
  features:
    - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
        custom_checkbox: true
  - tables

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/renataberoli
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/renataberoli/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/renataberoli
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/renataberoli/