site_name: Renata Beroli
site_url: https://renataberoli.github.io/
nav:
  - Bug Catcher: 'projects/bug_catcher.md'
  - Dockgrid: 'projects/dockgrid.md'
  - Neobiome BIM: 'projects/neobiome.md'
  - Microbiome Reports: 'projects/reports.md'
  - Test Cases: 'projects/test_case.md'

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
        custom_checkbox: true
  - tables